export const theme = {
  colors: {
    mainBg: '#121212',
    secondaryBg: '#121212',
    primaryColor: '#fafafa',
    primaryBlack: '#000',
    primaryGray: '#363636',
    secondaryGray: '#aaa',
    thidGray: '#3b3b3b',
    fourthGray: '#555',
    fifthGray: '#ccc',
    sixthGray: '#999',
    blue: '#0094f6',
    white: '#fff',
    errorMessage: '#721c24',
    errorMessageBg: '#f8d7da',
    errorMessageBorder: '#f5c6cb',
    successMessage: '#155724',
    successMessageBg: '#daedda',
    successMessageBorder: '#c3e6cb',
  },
};
